pipeline {
  agent {
    kubernetes {
      cloud 'terralogic-eks-agent'
      namespace 'cloudbees-builds'
      inheritFrom 'jenkins-kaniko-agent'
      defaultContainer 'jnlp'
    }
  }

  options {
    disableConcurrentBuilds()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }

  environment {
    MAVEN_REPO     = 'maven-repo'
    MVN_CACHE_NAME = 'mvn-cache'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-pat',
            url: 'https://github.com/kamalakar22/board_game.git'
      }
    }

    stage('Restore Maven Cache (S3)') {
      steps {
        sh 'mkdir -p "$MAVEN_REPO"'
        readCache name: "${MVN_CACHE_NAME}"
      }
    }

    stage('Maven Build') {
      steps {
        sh '''
          mvn clean install \
            -Dmaven.repo.local="$MAVEN_REPO"
        '''
      }
    }

    stage('Save Maven Cache (S3)') {
      steps {
        writeCache(
          name: "${MVN_CACHE_NAME}",
          includes: "${MAVEN_REPO}/**"
        )
      }
    }
  }

  post {
    always {
      deleteDir()   // required for k8s ephemeral pods
    }
  }
}
