pipeline {
  agent {
    kubernetes {
      cloud 'terralogic-eks-agent'
      namespace 'cloudbees-builds'
      inheritFrom 'jenkins-kaniko-agent'
      defaultContainer 'jnlp'
    }
  }

  options {
    disableConcurrentBuilds()
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }

  environment {
    NPM_CACHE_DIR  = 'node_modules'
    NPM_CACHE_NAME = 'npm-cache'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-pat',
            url: 'https://github.com/terralogic-fnc/youtube-clone.git'
      }
    }

    stage('Restore NPM Cache') {
      steps {
        sh 'mkdir -p "$NPM_CACHE_DIR"'
        readCache name: "${NPM_CACHE_NAME}"
      }
    }

    stage('Install Dependencies') {
      steps {
        sh '''
          npm install
        '''
      }
    }

    stage('Save NPM Cache') {
      steps {
        writeCache(
          name: "${NPM_CACHE_NAME}",
          includes: "${NPM_CACHE_DIR}/**"
        )
      }
    }
  }

  post {
    always {
      deleteDir()   // required for k8s ephemeral pods
    }
  }
}
